<?php
return array (
  88 => 
  array (
    'id' => '88',
    'catid' => '30',
    'typeid' => '0',
    'title' => 'unity iOS bulid 教程及remote 模式',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity bulid 教程',
    'description' => '常规bulid环境 unity 3 5 b6 pro + xcode 4 2 1 + ipad2 ios5 0 1 从来没有问题设置和安装 provisioning 这步有问题的朋友    ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=30&id=88',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391167932',
    'updatetime' => '1497158163',
    'video_url' => '',
    'hitsid' => 'c-1-88',
    'views' => '169',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '3',
    'monthviews' => '6',
  ),
  85 => 
  array (
    'id' => '85',
    'catid' => '30',
    'typeid' => '0',
    'title' => '一些iOS高效开源类库(转)',
    'style' => '',
    'thumb' => '',
    'keywords' => '一些 高效 开源',
    'description' => '因为iOS SDK相对比较底层，所以开发者就得受累多做一些体力活。不过幸运的是，有很多第三方的类库可以用来简化很多不必要的工作。笔者整理   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=30&id=85',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391166881',
    'updatetime' => '1491834000',
    'video_url' => '',
    'hitsid' => 'c-1-85',
    'views' => '150',
    'yesterdayviews' => '1',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  87 => 
  array (
    'id' => '87',
    'catid' => '30',
    'typeid' => '0',
    'title' => 'unity ios 详细改字体及size教程 ',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity 详细 字体',
    'description' => '针对mac用户1 Applications-&gt;Font book2 选中一个字体右键点show in finder3 copy ttf 文件到你的unity assets目录下面 或者在unity   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=30&id=87',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391167244',
    'updatetime' => '1497395069',
    'video_url' => '',
    'hitsid' => 'c-1-87',
    'views' => '82',
    'yesterdayviews' => '1',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '4',
  ),
  86 => 
  array (
    'id' => '86',
    'catid' => '30',
    'typeid' => '0',
    'title' => 'unity3D手机开发中的三维重力感应效果',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3D 手机 开发',
    'description' => '和2D一样，还是用到Input acceleration;但不同的是，3D中要得把世界坐标转化成屏幕坐标，这个方法前面有提到过，就是WorldToScreenPoint,再   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=30&id=86',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391167006',
    'updatetime' => '1491919911',
    'video_url' => '',
    'hitsid' => 'c-1-86',
    'views' => '61',
    'yesterdayviews' => '4',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>