<?php
return array (
  44 => 
  array (
    'id' => '44',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3d旋转摄像机脚本',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3d 旋转 摄像机',
    'description' => '1voidUpdate()2{3if(Input.GetMouseButton(1))4{5if(axes==RotationAxes.MouseXAndY)6{7//Readthemouseinputaxis8rotationX+=Input.GetAxis...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=44',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319453',
    'updatetime' => '1508032611',
    'video_url' => '',
    'hitsid' => 'c-1-44',
    'views' => '2779',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '5',
    'monthviews' => '5',
  ),
  79 => 
  array (
    'id' => '79',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3D中Gui button双击代码方法',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3D button 双击',
    'description' => '一个做双击效果的方法用两个按钮，点1出现2 2里写事件。var a=0 0;var b=0;function OnGUI(){if(a==0){if(GUI Button (Rect(10,10,100   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=79',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391161856',
    'updatetime' => '1508136179',
    'video_url' => '',
    'hitsid' => 'c-1-79',
    'views' => '2347',
    'yesterdayviews' => '1',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '7',
  ),
  80 => 
  array (
    'id' => '80',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3d之实现全屏窗口 gui焦点不错位 ',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131055757870.png',
    'keywords' => 'unity3d 实现 全屏',
    'description' => '关于unity进行全屏窗体的实现例子貌似不多，基本上思路都是用user32 dll来搞定。但是大多数都会出现焦点错位，或者3D画面由于窗口拉伸而变   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=80',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391162251',
    'updatetime' => '1508102486',
    'video_url' => '',
    'hitsid' => 'c-1-80',
    'views' => '1861',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '7',
  ),
  47 => 
  array (
    'id' => '47',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity脚本 动态改变模型大小、方向',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity 脚本 动态',
    'description' => '1本帖最后由Developer于2012-6-1408:53编辑publicvarmySkin:GUISkin;2varwindowRect=Rect(0,20,200,150);3varSliderScaleValue:float=0.0;4...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=47',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319627',
    'updatetime' => '1507991264',
    'video_url' => '',
    'hitsid' => 'c-1-47',
    'views' => '1688',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '5',
    'monthviews' => '5',
  ),
  81 => 
  array (
    'id' => '81',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'Unity3d水下模糊效果',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131060101678.png',
    'keywords' => 'Unity3d 水下 模糊',
    'description' => '这个教程大部分使用的是U3D内置的资源,使用到的水下模糊效果也仅仅是添加了Depth Of Field特效,用于模拟水下效果,下面有两种触发方式的讲   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=81',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391162404',
    'updatetime' => '1508094589',
    'video_url' => '',
    'hitsid' => 'c-1-81',
    'views' => '1557',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  54 => 
  array (
    'id' => '54',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'EZGUI基本操作简单介绍',
    'style' => '',
    'thumb' => 'http://game.ceeger.com/pictures/2011/12/HLZm9M.png',
    'keywords' => 'EZGUI 基本 操作',
    'description' => '官方的GUI根本无法跟EZGUI比，无论是资源还是易用性还是速度。EZGUI基于Mesh不占DrawCall。EZGUI是自动合并Mesh成为一个物体，并且贴图自动...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=54',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363335038',
    'updatetime' => '1508048057',
    'video_url' => '',
    'hitsid' => 'c-1-54',
    'views' => '669',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  43 => 
  array (
    'id' => '43',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'Unity3D AI人工智能（坦克模型自动寻怪，自动追击）',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Unity3D 人工智能 坦克',
    'description' => '12&lt;P&gt;功能：&lt;/P&gt;3&lt;P&gt;1，坦克自动旋转炮管，自动瞄准42，在坦克的射程之内自动开炮53，坦克自动向你追击&lt;/P&gt;复制代码6varEnemy_tank:GameObj...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=43',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319413',
    'updatetime' => '1498149053',
    'video_url' => '',
    'hitsid' => 'c-1-43',
    'views' => '422',
    'yesterdayviews' => '4',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '3',
  ),
  46 => 
  array (
    'id' => '46',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'Unity3d模型导入技巧',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Unity3d 模型 导入',
    'description' => 'Unity3d导入3dMax模型会产生若干问题，按照官方的说明，将max模型导成fbx文件导入untiy似乎也不能解决1、x轴向偏转3dmax模型导入后自动有一...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=46',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319581',
    'updatetime' => '1498139925',
    'video_url' => '',
    'hitsid' => 'c-1-46',
    'views' => '416',
    'yesterdayviews' => '1',
    'dayviews' => '10',
    'weekviews' => '10',
    'monthviews' => '27',
  ),
  40 => 
  array (
    'id' => '40',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3d动态读取外部文件',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3d 动态 读取',
    'description' => '分两种情况：1，加载封装好的内部文件。viewplaincopytoclipboardprint?varaaa:Material;//空材质varbbb:GameObject;//要绑定材质的模型fun...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=40',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363318872',
    'updatetime' => '1495107394',
    'video_url' => '',
    'hitsid' => 'c-1-40',
    'views' => '274',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  42 => 
  array (
    'id' => '42',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'Unity3D里面的JavaScript和浏览器的JavaScript的大致区别',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Unity3D 里面 JavaScript',
    'description' => '我从前做过一点JavaScript的东西，和同事加起来大概写过将近2M的JavaScript脚本，粗看了一下Unity中的JavaScript，和从前所了解的基于Brows...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=42',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319291',
    'updatetime' => '1497801453',
    'video_url' => '',
    'hitsid' => 'c-1-42',
    'views' => '261',
    'yesterdayviews' => '6',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '12',
  ),
);
?>