<?php
return array (
  70 => 
  array (
    'id' => '70',
    'catid' => '22',
    'typeid' => '0',
    'title' => '全息技术镜面投影应用',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0411/20130411025052507.jpg',
    'keywords' => '全息 技术 镜面',
    'description' => '      采用虚拟现实软件内容结合镜面式全息投影应用我们追求完美的视觉，我们凭借领先世界的技术、精密的设计、突破性的创新，推出拥...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=22&id=70',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1365661989',
    'updatetime' => '1507707140',
    'video_url' => '',
    'hitsid' => 'c-1-70',
    'views' => '378',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  67 => 
  array (
    'id' => '67',
    'catid' => '22',
    'typeid' => '0',
    'title' => '朗途全息技术简介',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0409/20130409123751491.jpg',
    'keywords' => '朗途 全息',
    'description' => '我们追求完美的视觉，我们凭借领先世界的技术、精密的设计、突破性的创新，推出拥有世界专利技术的全息空间投影荧屏系列。仅厚0.2mm的全息...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=22&id=67',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1365477638',
    'updatetime' => '1507707149',
    'video_url' => '',
    'hitsid' => 'c-1-67',
    'views' => '158',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>