<?php
return array (
  82 => 
  array (
    'id' => '82',
    'catid' => '29',
    'typeid' => '0',
    'title' => 'Arduino教程（提高篇）——SR04超声波类库的使用',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131061518868.jpg',
    'keywords' => 'Arduino 教程 提高',
    'description' => 'SR04是最常见的超声波传感器之一，价格便宜，好用，是arduino开发的必备良品~10490479igv91g1nd1n9a1 jpg (78 92 KB, 下载次数: 51)下   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=29&id=82',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391163163',
    'updatetime' => '1508127769',
    'video_url' => '',
    'hitsid' => 'c-1-82',
    'views' => '2119',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '6',
  ),
  55 => 
  array (
    'id' => '55',
    'catid' => '29',
    'typeid' => '0',
    'title' => '安卓手机控制的arduino双足行走机器人',
    'style' => '',
    'thumb' => '',
    'keywords' => '手机 控制 arduino',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=29&id=55',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363335967',
    'updatetime' => '1498229776',
    'video_url' => '',
    'hitsid' => 'c-1-55',
    'views' => '678',
    'yesterdayviews' => '1',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '8',
  ),
);
?>