<?php
return array (
  65 => 
  array (
    'id' => '65',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟现实飞机演示系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0307/20130307111759673.jpg',
    'keywords' => '虚拟现实 飞机 演示',
    'description' => '  虚拟现实飞机演示系统，是通过虚拟现实平台，将不同型号的客机外观直观的展示给客户的一种解决方案，此方案的优势是可以将不同型号的飞...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=65',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1361433960',
    'updatetime' => '1487638206',
    'video_url' => '',
    'hitsid' => 'c-1-65',
    'views' => '347',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '5',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '14',
    'typeid' => '0',
    'title' => '电动汽车加电站规划设计',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114092548848.jpg',
    'keywords' => '电动汽车 加电站',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=1',
    'listorder' => '5',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358169855',
    'updatetime' => '1466977808',
    'video_url' => '',
    'hitsid' => 'c-1-1',
    'views' => '34',
    'yesterdayviews' => '2',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  58 => 
  array (
    'id' => '58',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟现实飞机演示系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0307/20130307111759673.jpg',
    'keywords' => '虚拟现实 飞机 演示',
    'description' => '  虚拟现实飞机演示系统，是通过虚拟现实平台，将不同型号的客机外观直观的展示给客户的一种解决方案，此方案的优势是可以将不同型号的飞...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=58',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363864490',
    'updatetime' => '1497940014',
    'video_url' => '',
    'hitsid' => 'c-1-58',
    'views' => '57',
    'yesterdayviews' => '2',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  61 => 
  array (
    'id' => '61',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟漫游欧式教堂',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0305/20130305062059578.jpg',
    'keywords' => '虚拟 漫游 欧式',
    'description' => ' 朗途科技携手普兰德广告公司打造概念型web3d产品，针对欧式建筑，欧洲文化，教堂文化在华和亚洲地区的推广。产品依托虚拟现实技术制作了...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=61',
    'listorder' => '7',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1364283725',
    'updatetime' => '1466977804',
    'video_url' => '',
    'hitsid' => 'c-1-61',
    'views' => '29',
    'yesterdayviews' => '2',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '14',
    'typeid' => '0',
    'title' => '网上虚拟旅游求佛系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114092838198.jpg',
    'keywords' => 'web3d  虚拟 旅游',
    'description' => '网上虚拟旅游求佛系统',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=2',
    'listorder' => '4',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358170093',
    'updatetime' => '1498296316',
    'video_url' => '',
    'hitsid' => 'c-1-2',
    'views' => '119',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '3',
  ),
  92 => 
  array (
    'id' => '92',
    'catid' => '14',
    'typeid' => '0',
    'title' => '汽车三维竞速游戏开发',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2016/0610/20160610033855975.jpg',
    'keywords' => '三维 竞速 汽车',
    'description' => '广州车展由北京朗途科技公司开发的三维试驾游戏引来了不少小伙伴的驻足体验。小朋友，大朋友，外国朋友都争相体验一把给元首当司机的乐趣。   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=92',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1465544625',
    'updatetime' => '1508063962',
    'video_url' => '',
    'hitsid' => 'c-1-92',
    'views' => '75',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟驾驶仿真培训',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114092931108.jpg',
    'keywords' => '虚拟 驾驶 仿真',
    'description' => ' 交通道路虚拟仿真培训系统是北京朗途科技有限责任公司为客货运司机交通训考试打造的一款仿真培训软件。软件主要采用虚拟现实技术，通过计...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=3',
    'listorder' => '3',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358170152',
    'updatetime' => '1497505817',
    'video_url' => '',
    'hitsid' => 'c-1-3',
    'views' => '536',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
  64 => 
  array (
    'id' => '64',
    'catid' => '14',
    'typeid' => '0',
    'title' => '网上虚拟旅游求佛系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0502/20130502121635704.jpg',
    'keywords' => 'web3d 虚拟 旅游',
    'description' => ' web3d产品是虚拟现实技术的一个分支领域。从某种意义上讲广为人知的三维网游就是web3d技术的一种应用。由于国内网络环境的瓶颈限制了这项...',
    'posids' => '1',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=64',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1355990580',
    'updatetime' => '1508150662',
    'video_url' => '',
    'hitsid' => 'c-1-64',
    'views' => '188',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
);
?>