<?php
return array (
  62 => 
  array (
    'id' => '62',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟现实汽车展示',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0218/20130218063420302.jpg',
    'keywords' => '虚拟现实 汽车 展示',
    'description' => '虚拟现实汽车展示软件定义为何种产品？朗途科技虚拟现实汽车展示软件从技术角度可以定义为是一款利用计算机三维软件按照实车比例和外观内饰...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=62',
    'listorder' => '8',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1357976700',
    'updatetime' => '1497939980',
    'video_url' => '',
    'hitsid' => 'c-1-62',
    'views' => '791',
    'yesterdayviews' => '1',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '8',
  ),
  73 => 
  array (
    'id' => '73',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟驾驶仿真培训',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114092931108.jpg',
    'keywords' => '虚拟 驾驶 仿真',
    'description' => ' 交通道路虚拟仿真培训系统是北京朗途科技有限责任公司为客货运司机交通训考试打造的一款仿真培训软件。软件主要采用虚拟现实技术，通过计...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=73',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1367459502',
    'updatetime' => '1497940154',
    'video_url' => '',
    'hitsid' => 'c-1-73',
    'views' => '227',
    'yesterdayviews' => '6',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '7',
  ),
  65 => 
  array (
    'id' => '65',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟现实飞机演示系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0307/20130307111759673.jpg',
    'keywords' => '虚拟现实 飞机 演示',
    'description' => '  虚拟现实飞机演示系统，是通过虚拟现实平台，将不同型号的客机外观直观的展示给客户的一种解决方案，此方案的优势是可以将不同型号的飞...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=65',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1361433960',
    'updatetime' => '1487638206',
    'video_url' => '',
    'hitsid' => 'c-1-65',
    'views' => '347',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '5',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '14',
    'typeid' => '0',
    'title' => '电动汽车加电站规划设计',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114092548848.jpg',
    'keywords' => '电动汽车 加电站',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=1',
    'listorder' => '5',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358169855',
    'updatetime' => '1466977808',
    'video_url' => '',
    'hitsid' => 'c-1-1',
    'views' => '34',
    'yesterdayviews' => '2',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  58 => 
  array (
    'id' => '58',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟现实飞机演示系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0307/20130307111759673.jpg',
    'keywords' => '虚拟现实 飞机 演示',
    'description' => '  虚拟现实飞机演示系统，是通过虚拟现实平台，将不同型号的客机外观直观的展示给客户的一种解决方案，此方案的优势是可以将不同型号的飞...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=58',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363864490',
    'updatetime' => '1497940014',
    'video_url' => '',
    'hitsid' => 'c-1-58',
    'views' => '57',
    'yesterdayviews' => '2',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  61 => 
  array (
    'id' => '61',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟漫游欧式教堂',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0305/20130305062059578.jpg',
    'keywords' => '虚拟 漫游 欧式',
    'description' => ' 朗途科技携手普兰德广告公司打造概念型web3d产品，针对欧式建筑，欧洲文化，教堂文化在华和亚洲地区的推广。产品依托虚拟现实技术制作了...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=61',
    'listorder' => '7',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1364283725',
    'updatetime' => '1466977804',
    'video_url' => '',
    'hitsid' => 'c-1-61',
    'views' => '29',
    'yesterdayviews' => '2',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '14',
    'typeid' => '0',
    'title' => '网上虚拟旅游求佛系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114092838198.jpg',
    'keywords' => 'web3d  虚拟 旅游',
    'description' => '网上虚拟旅游求佛系统',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=2',
    'listorder' => '4',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358170093',
    'updatetime' => '1498296316',
    'video_url' => '',
    'hitsid' => 'c-1-2',
    'views' => '119',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '3',
  ),
  63 => 
  array (
    'id' => '63',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟驾驶仿真培训',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0217/20130217033223273.jpg',
    'keywords' => '虚拟 驾驶 仿真',
    'description' => ' 交通道路虚拟仿真培训系统是北京朗途科技有限责任公司为客货运司机交通训考试打造的一款仿真培训软件。软件主要采用虚拟现实技术，通过计...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=63',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1353657660',
    'updatetime' => '1497809118',
    'video_url' => '',
    'hitsid' => 'c-1-63',
    'views' => '86',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '3',
  ),
);
?>