<?php
return array (
  24 => 
  array (
    'id' => '24',
    'catid' => '6',
    'typeid' => '0',
    'title' => '军事仿真',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0115/20130115103750368.jpg',
    'keywords' => '军事 仿真',
    'description' => '军事仿真 军事仿真',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=6&id=24',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358260661',
    'updatetime' => '1497514830',
    'video_url' => '',
    'hitsid' => 'c-1-24',
    'views' => '143',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '6',
    'typeid' => '0',
    'title' => '古迹复原',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0115/20130115103732956.jpg',
    'keywords' => '古迹 复原',
    'description' => '古迹复原',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=6&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358260638',
    'updatetime' => '1497514827',
    'video_url' => '',
    'hitsid' => 'c-1-23',
    'views' => '75',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  21 => 
  array (
    'id' => '21',
    'catid' => '6',
    'typeid' => '0',
    'title' => '地产应用',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0115/20130115103647665.jpg',
    'keywords' => '地产 应用',
    'description' => '地产应用',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=6&id=21',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358260589',
    'updatetime' => '1478787971',
    'video_url' => '',
    'hitsid' => 'c-1-21',
    'views' => '60',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '6',
    'typeid' => '0',
    'title' => '旅游仿真',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0115/20130115103708978.jpg',
    'keywords' => '旅游 仿真',
    'description' => '旅游仿真',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=6&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358260614',
    'updatetime' => '1474185987',
    'video_url' => '',
    'hitsid' => 'c-1-22',
    'views' => '39',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  20 => 
  array (
    'id' => '20',
    'catid' => '6',
    'typeid' => '0',
    'title' => '城市规划',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0115/20130115103620821.jpg',
    'keywords' => '城市规划',
    'description' => '城市规划',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=6&id=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358260533',
    'updatetime' => '1474023266',
    'video_url' => '',
    'hitsid' => 'c-1-20',
    'views' => '28',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>