<?php
return array (
  62 => 
  array (
    'id' => '62',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟现实汽车展示',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0218/20130218063420302.jpg',
    'keywords' => '虚拟现实 汽车 展示',
    'description' => '虚拟现实汽车展示软件定义为何种产品？朗途科技虚拟现实汽车展示软件从技术角度可以定义为是一款利用计算机三维软件按照实车比例和外观内饰...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=62',
    'listorder' => '8',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1357976700',
    'updatetime' => '1497939980',
    'video_url' => '',
    'hitsid' => 'c-1-62',
    'views' => '791',
    'yesterdayviews' => '1',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '8',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟驾驶仿真培训',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114092931108.jpg',
    'keywords' => '虚拟 驾驶 仿真',
    'description' => ' 交通道路虚拟仿真培训系统是北京朗途科技有限责任公司为客货运司机交通训考试打造的一款仿真培训软件。软件主要采用虚拟现实技术，通过计...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=3',
    'listorder' => '3',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358170152',
    'updatetime' => '1497505817',
    'video_url' => '',
    'hitsid' => 'c-1-3',
    'views' => '536',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
  65 => 
  array (
    'id' => '65',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟现实飞机演示系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0307/20130307111759673.jpg',
    'keywords' => '虚拟现实 飞机 演示',
    'description' => '  虚拟现实飞机演示系统，是通过虚拟现实平台，将不同型号的客机外观直观的展示给客户的一种解决方案，此方案的优势是可以将不同型号的飞...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=65',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1361433960',
    'updatetime' => '1487638206',
    'video_url' => '',
    'hitsid' => 'c-1-65',
    'views' => '347',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '5',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '14',
    'typeid' => '0',
    'title' => '新浪房产展示-虚拟样板间',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114093010756.jpg',
    'keywords' => '新浪 房产 展示',
    'description' => '新浪房产展示-虚拟样板间',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=4',
    'listorder' => '6',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358170198',
    'updatetime' => '1497646596',
    'video_url' => 'http://v.youku.com/v_show/id_XNDQ0MDg0Mzky.html',
    'hitsid' => 'c-1-4',
    'views' => '286',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  66 => 
  array (
    'id' => '66',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟驾车漫游北京',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2016/0609/thumb_800_415_20160327100917736.jpg',
    'keywords' => '虚拟 驾车 漫游',
    'description' => '项目需求：展示中国移动的手机导航产品给自驾车出行带来的便利服务。应用展厅为中国移动通信集团总部展厅，用于给中国移动的客户和相关领导   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=66',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1360310880',
    'updatetime' => '1496556086',
    'video_url' => '',
    'hitsid' => 'c-1-66',
    'views' => '270',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  73 => 
  array (
    'id' => '73',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟驾驶仿真培训',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114092931108.jpg',
    'keywords' => '虚拟 驾驶 仿真',
    'description' => ' 交通道路虚拟仿真培训系统是北京朗途科技有限责任公司为客货运司机交通训考试打造的一款仿真培训软件。软件主要采用虚拟现实技术，通过计...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=73',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1367459502',
    'updatetime' => '1497940154',
    'video_url' => '',
    'hitsid' => 'c-1-73',
    'views' => '227',
    'yesterdayviews' => '6',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '7',
  ),
  64 => 
  array (
    'id' => '64',
    'catid' => '14',
    'typeid' => '0',
    'title' => '网上虚拟旅游求佛系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0502/20130502121635704.jpg',
    'keywords' => 'web3d 虚拟 旅游',
    'description' => ' web3d产品是虚拟现实技术的一个分支领域。从某种意义上讲广为人知的三维网游就是web3d技术的一种应用。由于国内网络环境的瓶颈限制了这项...',
    'posids' => '1',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=64',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1355990580',
    'updatetime' => '1493315468',
    'video_url' => '',
    'hitsid' => 'c-1-64',
    'views' => '186',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  57 => 
  array (
    'id' => '57',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟驾车漫游北京',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0502/20130502121651199.jpg',
    'keywords' => '虚拟 驾车 漫游',
    'description' => '项目需求：展示中国移动的手机导航产品给自驾车出行带来的便利服务。应用展厅为中国移动通信集团总部展厅，用于给中国移动的客户和相关领导...',
    'posids' => '1',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=57',
    'listorder' => '2',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363667684',
    'updatetime' => '1497007899',
    'video_url' => '',
    'hitsid' => 'c-1-57',
    'views' => '151',
    'yesterdayviews' => '5',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '14',
    'typeid' => '0',
    'title' => '网上虚拟旅游求佛系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114092838198.jpg',
    'keywords' => 'web3d  虚拟 旅游',
    'description' => '网上虚拟旅游求佛系统',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=2',
    'listorder' => '4',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358170093',
    'updatetime' => '1498296316',
    'video_url' => '',
    'hitsid' => 'c-1-2',
    'views' => '119',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '3',
  ),
  63 => 
  array (
    'id' => '63',
    'catid' => '14',
    'typeid' => '0',
    'title' => '虚拟驾驶仿真培训',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0217/20130217033223273.jpg',
    'keywords' => '虚拟 驾驶 仿真',
    'description' => ' 交通道路虚拟仿真培训系统是北京朗途科技有限责任公司为客货运司机交通训考试打造的一款仿真培训软件。软件主要采用虚拟现实技术，通过计...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=14&id=63',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1353657660',
    'updatetime' => '1497809118',
    'video_url' => '',
    'hitsid' => 'c-1-63',
    'views' => '86',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '3',
  ),
);
?>