<?php
return array (
  44 => 
  array (
    'id' => '44',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3d旋转摄像机脚本',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3d 旋转 摄像机',
    'description' => '1voidUpdate()2{3if(Input.GetMouseButton(1))4{5if(axes==RotationAxes.MouseXAndY)6{7//Readthemouseinputaxis8rotationX+=Input.GetAxis...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=44',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319453',
    'updatetime' => '1508032611',
    'video_url' => '',
    'hitsid' => 'c-1-44',
    'views' => '2779',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '5',
    'monthviews' => '5',
  ),
  79 => 
  array (
    'id' => '79',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3D中Gui button双击代码方法',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3D button 双击',
    'description' => '一个做双击效果的方法用两个按钮，点1出现2 2里写事件。var a=0 0;var b=0;function OnGUI(){if(a==0){if(GUI Button (Rect(10,10,100   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=79',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391161856',
    'updatetime' => '1508109863',
    'video_url' => '',
    'hitsid' => 'c-1-79',
    'views' => '2346',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '6',
  ),
  77 => 
  array (
    'id' => '77',
    'catid' => '25',
    'typeid' => '0',
    'title' => 'unity3d/AR实现方案的对比',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3d 实现 方案',
    'description' => 'AR应用忽然就比较流行起来了，这是老外做一个unity3d AR解决方案的对比，有兴趣的朋友可以深入研究下！I have made a system which    ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=25&id=77',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391161378',
    'updatetime' => '1507940047',
    'video_url' => '',
    'hitsid' => 'c-1-77',
    'views' => '2165',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  82 => 
  array (
    'id' => '82',
    'catid' => '29',
    'typeid' => '0',
    'title' => 'Arduino教程（提高篇）——SR04超声波类库的使用',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131061518868.jpg',
    'keywords' => 'Arduino 教程 提高',
    'description' => 'SR04是最常见的超声波传感器之一，价格便宜，好用，是arduino开发的必备良品~10490479igv91g1nd1n9a1 jpg (78 92 KB, 下载次数: 51)下   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=29&id=82',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391163163',
    'updatetime' => '1508075997',
    'video_url' => '',
    'hitsid' => 'c-1-82',
    'views' => '2118',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '5',
    'monthviews' => '5',
  ),
  80 => 
  array (
    'id' => '80',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3d之实现全屏窗口 gui焦点不错位 ',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131055757870.png',
    'keywords' => 'unity3d 实现 全屏',
    'description' => '关于unity进行全屏窗体的实现例子貌似不多，基本上思路都是用user32 dll来搞定。但是大多数都会出现焦点错位，或者3D画面由于窗口拉伸而变   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=80',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391162251',
    'updatetime' => '1508102486',
    'video_url' => '',
    'hitsid' => 'c-1-80',
    'views' => '1861',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '7',
  ),
  49 => 
  array (
    'id' => '49',
    'catid' => '27',
    'typeid' => '0',
    'title' => '三维模型导入到vrp中报错的处理',
    'style' => '',
    'thumb' => '',
    'keywords' => '三维 模型 导入到',
    'description' => '以下错误提示解决方法如下：●错误提示：错误1:Line01:该模型所使用的第1号MapChannel没有初始化，请给该MapChannel指定正确的Uv坐标。　解...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=27&id=49',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363322858',
    'updatetime' => '1507816772',
    'video_url' => '',
    'hitsid' => 'c-1-49',
    'views' => '1696',
    'yesterdayviews' => '4',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  47 => 
  array (
    'id' => '47',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity脚本 动态改变模型大小、方向',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity 脚本 动态',
    'description' => '1本帖最后由Developer于2012-6-1408:53编辑publicvarmySkin:GUISkin;2varwindowRect=Rect(0,20,200,150);3varSliderScaleValue:float=0.0;4...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=47',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319627',
    'updatetime' => '1507991264',
    'video_url' => '',
    'hitsid' => 'c-1-47',
    'views' => '1688',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '5',
    'monthviews' => '5',
  ),
  81 => 
  array (
    'id' => '81',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'Unity3d水下模糊效果',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131060101678.png',
    'keywords' => 'Unity3d 水下 模糊',
    'description' => '这个教程大部分使用的是U3D内置的资源,使用到的水下模糊效果也仅仅是添加了Depth Of Field特效,用于模拟水下效果,下面有两种触发方式的讲   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=81',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391162404',
    'updatetime' => '1508094589',
    'video_url' => '',
    'hitsid' => 'c-1-81',
    'views' => '1557',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  39 => 
  array (
    'id' => '39',
    'catid' => '24',
    'typeid' => '0',
    'title' => '虚拟现实引擎比较',
    'style' => '',
    'thumb' => '',
    'keywords' => '虚拟现实 引擎 比较',
    'description' => '虚拟现实引擎的好坏问题争论了很久，相信也会一直争论下去，软件的好坏本身就是相对的，因此使用者更应该从自身的角度和所处的行业特点来选...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=24&id=39',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363318602',
    'updatetime' => '1497223834',
    'video_url' => '',
    'hitsid' => 'c-1-39',
    'views' => '1029',
    'yesterdayviews' => '5',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '15',
  ),
  55 => 
  array (
    'id' => '55',
    'catid' => '29',
    'typeid' => '0',
    'title' => '安卓手机控制的arduino双足行走机器人',
    'style' => '',
    'thumb' => '',
    'keywords' => '手机 控制 arduino',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=29&id=55',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363335967',
    'updatetime' => '1498229776',
    'video_url' => '',
    'hitsid' => 'c-1-55',
    'views' => '678',
    'yesterdayviews' => '1',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '8',
  ),
);
?>