<?php
return array (
  35 => 
  array (
    'id' => '35',
    'catid' => '20',
    'typeid' => '0',
    'title' => '朗途虚拟现实产品展厅和活动应用',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2016/0329/20160329101343333.jpg',
    'keywords' => '虚拟现实 产品 展厅',
    'description' => '以下是朗途科技研发的虚拟现实产品的部分应用。             虚拟现实房产销售应用01             虚拟现实房产   ',
    'posids' => '1',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=20&id=35',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1362538620',
    'updatetime' => '1508063927',
    'video_url' => '',
    'hitsid' => 'c-1-35',
    'views' => '3648',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  74 => 
  array (
    'id' => '74',
    'catid' => '20',
    'typeid' => '0',
    'title' => 'vr虚拟驾车漫游北京',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0227/20130227112751180.jpg',
    'keywords' => '虚拟 驾车 漫游',
    'description' => '项目需求：展示中国移动的手机导航产品给自驾车出行带来的便利服务。应用展厅为中国移动通信集团总部展厅，用于给中国移动的客户和相关领导   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=20&id=74',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1424917200',
    'updatetime' => '1508151708',
    'video_url' => '',
    'hitsid' => 'c-1-74',
    'views' => '2151',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '4',
  ),
  33 => 
  array (
    'id' => '33',
    'catid' => '20',
    'typeid' => '0',
    'title' => '加电站规划虚拟体验',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0217/20130217062626855.jpg',
    'keywords' => '电站 规划 虚拟',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=20&id=33',
    'listorder' => '7',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1361094416',
    'updatetime' => '1491630600',
    'video_url' => '',
    'hitsid' => 'c-1-33',
    'views' => '102',
    'yesterdayviews' => '2',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  29 => 
  array (
    'id' => '29',
    'catid' => '20',
    'typeid' => '0',
    'title' => '虚拟房产体验',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114093010756.jpg',
    'keywords' => '虚拟 房产 体验',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=20&id=29',
    'listorder' => '4',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1361080272',
    'updatetime' => '1496202781',
    'video_url' => '',
    'hitsid' => 'c-1-29',
    'views' => '216',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  32 => 
  array (
    'id' => '32',
    'catid' => '20',
    'typeid' => '0',
    'title' => '远程虚拟旅游系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0217/20130217062819557.jpg',
    'keywords' => '远程 虚拟 旅游',
    'description' => ' web3d产品是虚拟现实技术的一个分支领域。从某种意义上讲广为人知的三维网游就是web3d技术的一种应用。由于国内网络环境的瓶颈限制了这项...',
    'posids' => '1',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=20&id=32',
    'listorder' => '2',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1361089516',
    'updatetime' => '1508063935',
    'video_url' => '',
    'hitsid' => 'c-1-32',
    'views' => '3242',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  31 => 
  array (
    'id' => '31',
    'catid' => '20',
    'typeid' => '0',
    'title' => '虚拟驾驶仿真培训',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0114/20130114092931108.jpg',
    'keywords' => '虚拟 驾驶 仿真',
    'description' => ' 交通道路虚拟仿真培训系统是北京朗途科技有限责任公司为客货运司机交通训考试打造的一款仿真培训软件。软件主要采用虚拟现实技术，通过计...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=20&id=31',
    'listorder' => '8',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1361088389',
    'updatetime' => '1508094819',
    'video_url' => '',
    'hitsid' => 'c-1-31',
    'views' => '98',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  34 => 
  array (
    'id' => '34',
    'catid' => '20',
    'typeid' => '0',
    'title' => '虚拟现实汽车展示',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0218/20130218050835475.jpg',
    'keywords' => '虚拟现实 汽车 展示',
    'description' => '虚拟现实汽车展示软件定义为何种...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=20&id=34',
    'listorder' => '3',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1361178498',
    'updatetime' => '1496318244',
    'video_url' => '',
    'hitsid' => 'c-1-34',
    'views' => '387',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  36 => 
  array (
    'id' => '36',
    'catid' => '20',
    'typeid' => '0',
    'title' => '虚拟漫游欧式教堂',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0305/thumb_200_200_20130305062531150.jpg',
    'keywords' => '虚拟 漫游 欧式',
    'description' => ' 朗途科技携手普兰德广告公司打造概念型web3d产品，针对欧式建筑，欧洲文化，教堂文化在华和亚洲地区的推广。产品依托虚拟现实技术制作了...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=20&id=36',
    'listorder' => '6',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1362478382',
    'updatetime' => '1496317815',
    'video_url' => '',
    'hitsid' => 'c-1-36',
    'views' => '189',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  37 => 
  array (
    'id' => '37',
    'catid' => '20',
    'typeid' => '0',
    'title' => '虚拟现实飞机外观演示系统',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0307/20130307112444860.jpg',
    'keywords' => '虚拟现实 飞机 外观',
    'description' => '  虚拟现实飞机演示系统，是通过虚拟现实平台，将不同型号的客机外观只管的展示给客户的一种解决方案，此方案的优势是可以将不同型号的飞...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=20&id=37',
    'listorder' => '5',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1362626043',
    'updatetime' => '1496317822',
    'video_url' => '',
    'hitsid' => 'c-1-37',
    'views' => '155',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>