<?php
return array (
  51 => 
  array (
    'id' => '51',
    'catid' => '28',
    'typeid' => '0',
    'title' => 'Kinect骨骼数据与彩色影像和深度影像的对齐',
    'style' => '',
    'thumb' => 'http://images.cnblogs.com/cnblogs_com/yangecnu/201212/201212092313525795.png',
    'keywords' => 'Kinect 骨骼 数据',
    'description' => 'Kinect骨骼数据与彩色影像和深度影像的对齐 很多同学留言问怎么讲两种影像数据显示在同一张屏幕上，也就是说怎么将骨骼数据叠加到彩色影像...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=28&id=51',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363330519',
    'updatetime' => '1496838798',
    'video_url' => '',
    'hitsid' => 'c-1-51',
    'views' => '622',
    'yesterdayviews' => '6',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  52 => 
  array (
    'id' => '52',
    'catid' => '28',
    'typeid' => '0',
    'title' => '使用Kinect测量身高',
    'style' => '',
    'thumb' => 'http://images.cnblogs.com/cnblogs_com/yangecnu/201211/201211120131281176.png',
    'keywords' => '使用 Kinect 测量',
    'description' => '使用Kinect测量身高 使用Kinect测量身高的方法其实有很多种： 第一种方式是使用Kinect的视场角以及结合一些三角形几何运算，就可以大致测...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=28&id=52',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363330782',
    'updatetime' => '1498217338',
    'video_url' => '',
    'hitsid' => 'c-1-52',
    'views' => '401',
    'yesterdayviews' => '1',
    'dayviews' => '7',
    'weekviews' => '15',
    'monthviews' => '16',
  ),
  84 => 
  array (
    'id' => '84',
    'catid' => '28',
    'typeid' => '0',
    'title' => '最新修正OpenNI和Kinect安装中文教程 ',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131065805442.png',
    'keywords' => '最新 修正 OpenNI',
    'description' => '利用PrimeSence公司放出的驱动，在PC平台上安装Kinect的中文教程。硬件需求：Kinect一台（价格：1200RMB左右）连接Kinect和PC的USB转换接口   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=28&id=84',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391164152',
    'updatetime' => '1479086869',
    'video_url' => '',
    'hitsid' => 'c-1-84',
    'views' => '38',
    'yesterdayviews' => '2',
    'dayviews' => '6',
    'weekviews' => '6',
    'monthviews' => '6',
  ),
  83 => 
  array (
    'id' => '83',
    'catid' => '28',
    'typeid' => '0',
    'title' => '[转]关于体感游戏的一些思考（二） --- POV和基本场景',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131062706626.gif',
    'keywords' => '',
    'description' => '从口语和故事讲述中借用术语来比喻游戏的观察点（Point of View）很常见。第一人称射击类使得你可以以游戏角色的视觉看到屏幕下方自己虚   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=28&id=83',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391163775',
    'updatetime' => '1479086877',
    'video_url' => '',
    'hitsid' => 'c-1-83',
    'views' => '36',
    'yesterdayviews' => '2',
    'dayviews' => '5',
    'weekviews' => '5',
    'monthviews' => '5',
  ),
);
?>