<?php
return array (
  39 => 
  array (
    'id' => '39',
    'catid' => '24',
    'typeid' => '0',
    'title' => '虚拟现实引擎比较',
    'style' => '',
    'thumb' => '',
    'keywords' => '虚拟现实 引擎 比较',
    'description' => '虚拟现实引擎的好坏问题争论了很久，相信也会一直争论下去，软件的好坏本身就是相对的，因此使用者更应该从自身的角度和所处的行业特点来选...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=24&id=39',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363318602',
    'updatetime' => '1497223834',
    'video_url' => '',
    'hitsid' => 'c-1-39',
    'views' => '1029',
    'yesterdayviews' => '5',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '15',
  ),
  50 => 
  array (
    'id' => '50',
    'catid' => '24',
    'typeid' => '0',
    'title' => '虚拟现实简介',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0227/20130227111654363.jpg',
    'keywords' => '虚拟现实 简介',
    'description' => '虚拟现实 ，英文名为 Virtual Reality ，也被称之为三维虚拟现实和虚拟现实仿真。这一名词是                       ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=24&id=50',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363324740',
    'updatetime' => '1487658321',
    'video_url' => '',
    'hitsid' => 'c-1-50',
    'views' => '82',
    'yesterdayviews' => '4',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>