<?php
return array (
  38 => 
  array (
    'id' => '38',
    'catid' => '21',
    'typeid' => '0',
    'title' => '增强现实移动端Mobile-AR',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0312/20130312053149733.jpg',
    'keywords' => '增强现实 产品',
    'description' => '朗途科技打造增强现实软件搭载手机，平板电脑的硬件设备。 根据客户的需求我们可以为您订制研发不同的增强现实产品，可以使原本内容单一的...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=21&id=38',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363053018',
    'updatetime' => '1497750971',
    'video_url' => '',
    'hitsid' => 'c-1-38',
    'views' => '589',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '6',
    'monthviews' => '7',
  ),
  68 => 
  array (
    'id' => '68',
    'catid' => '21',
    'typeid' => '0',
    'title' => '增强现实图像识别交互',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0326/20130326033022840.jpg',
    'keywords' => '增强 现实 图像',
    'description' => '指定图像的识别和判断，根据不同图案的卡片，在显示设备中呈现出不同的预制模型，每张图片都带给你不同的惊奇感受。',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=21&id=68',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1365482459',
    'updatetime' => '1494854532',
    'video_url' => '',
    'hitsid' => 'c-1-68',
    'views' => '317',
    'yesterdayviews' => '1',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  56 => 
  array (
    'id' => '56',
    'catid' => '21',
    'typeid' => '0',
    'title' => '增强现实在产品发布会的应用',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0322/20130322110526834.jpg',
    'keywords' => '增强现实 产品',
    'description' => ' 增强现实(AR)产品在很多高新领域做产品发布会时都有广泛应用。汽车，手表，高端奢侈品在做发布会时更是对增强现实这门展示手段表现出极大...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=21&id=56',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363338474',
    'updatetime' => '1494854556',
    'video_url' => '',
    'hitsid' => 'c-1-56',
    'views' => '304',
    'yesterdayviews' => '1',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  69 => 
  array (
    'id' => '69',
    'catid' => '21',
    'typeid' => '0',
    'title' => '增强现实展览展示应用',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0502/20130502121621497.jpg',
    'keywords' => '增强 现实 展览展示',
    'description' => '国内客户如有视频中类似的需求可以联系北京朗途科技，我们志在打造国内最专业的虚拟现实和增强现实产品...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=20&id=69',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1365482575',
    'updatetime' => '1496317821',
    'video_url' => '',
    'hitsid' => 'c-1-69',
    'views' => '296',
    'yesterdayviews' => '1',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
);
?>