<?php
return array (
  82 => 
  array (
    'id' => '82',
    'catid' => '29',
    'typeid' => '0',
    'title' => 'Arduino教程（提高篇）——SR04超声波类库的使用',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131061518868.jpg',
    'keywords' => 'Arduino 教程 提高',
    'description' => 'SR04是最常见的超声波传感器之一，价格便宜，好用，是arduino开发的必备良品~10490479igv91g1nd1n9a1 jpg (78 92 KB, 下载次数: 51)下   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=29&id=82',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391163163',
    'updatetime' => '1498357826',
    'video_url' => '',
    'hitsid' => 'c-1-82',
    'views' => '2113',
    'yesterdayviews' => '4',
    'dayviews' => '3',
    'weekviews' => '16',
    'monthviews' => '70',
  ),
  49 => 
  array (
    'id' => '49',
    'catid' => '27',
    'typeid' => '0',
    'title' => '三维模型导入到vrp中报错的处理',
    'style' => '',
    'thumb' => '',
    'keywords' => '三维 模型 导入到',
    'description' => '以下错误提示解决方法如下：●错误提示：错误1:Line01:该模型所使用的第1号MapChannel没有初始化，请给该MapChannel指定正确的Uv坐标。　解...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=27&id=49',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363322858',
    'updatetime' => '1498367193',
    'video_url' => '',
    'hitsid' => 'c-1-49',
    'views' => '1694',
    'yesterdayviews' => '4',
    'dayviews' => '7',
    'weekviews' => '14',
    'monthviews' => '44',
  ),
  77 => 
  array (
    'id' => '77',
    'catid' => '25',
    'typeid' => '0',
    'title' => 'unity3d/AR实现方案的对比',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3d 实现 方案',
    'description' => 'AR应用忽然就比较流行起来了，这是老外做一个unity3d AR解决方案的对比，有兴趣的朋友可以深入研究下！I have made a system which    ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=25&id=77',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391161378',
    'updatetime' => '1498323088',
    'video_url' => '',
    'hitsid' => 'c-1-77',
    'views' => '2164',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '12',
    'monthviews' => '42',
  ),
  47 => 
  array (
    'id' => '47',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity脚本 动态改变模型大小、方向',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity 脚本 动态',
    'description' => '1本帖最后由Developer于2012-6-1408:53编辑publicvarmySkin:GUISkin;2varwindowRect=Rect(0,20,200,150);3varSliderScaleValue:float=0.0;4...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=47',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319627',
    'updatetime' => '1498226874',
    'video_url' => '',
    'hitsid' => 'c-1-47',
    'views' => '1683',
    'yesterdayviews' => '3',
    'dayviews' => '6',
    'weekviews' => '11',
    'monthviews' => '39',
  ),
  79 => 
  array (
    'id' => '79',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3D中Gui button双击代码方法',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3D button 双击',
    'description' => '一个做双击效果的方法用两个按钮，点1出现2 2里写事件。var a=0 0;var b=0;function OnGUI(){if(a==0){if(GUI Button (Rect(10,10,100   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=79',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391161856',
    'updatetime' => '1498287200',
    'video_url' => '',
    'hitsid' => 'c-1-79',
    'views' => '2340',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '8',
    'monthviews' => '35',
  ),
  44 => 
  array (
    'id' => '44',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3d旋转摄像机脚本',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3d 旋转 摄像机',
    'description' => '1voidUpdate()2{3if(Input.GetMouseButton(1))4{5if(axes==RotationAxes.MouseXAndY)6{7//Readthemouseinputaxis8rotationX+=Input.GetAxis...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=44',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319453',
    'updatetime' => '1498288969',
    'video_url' => '',
    'hitsid' => 'c-1-44',
    'views' => '2774',
    'yesterdayviews' => '1',
    'dayviews' => '3',
    'weekviews' => '5',
    'monthviews' => '27',
  ),
  46 => 
  array (
    'id' => '46',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'Unity3d模型导入技巧',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Unity3d 模型 导入',
    'description' => 'Unity3d导入3dMax模型会产生若干问题，按照官方的说明，将max模型导成fbx文件导入untiy似乎也不能解决1、x轴向偏转3dmax模型导入后自动有一...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=46',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319581',
    'updatetime' => '1498139925',
    'video_url' => '',
    'hitsid' => 'c-1-46',
    'views' => '416',
    'yesterdayviews' => '1',
    'dayviews' => '10',
    'weekviews' => '10',
    'monthviews' => '27',
  ),
  81 => 
  array (
    'id' => '81',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'Unity3d水下模糊效果',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131060101678.png',
    'keywords' => 'Unity3d 水下 模糊',
    'description' => '这个教程大部分使用的是U3D内置的资源,使用到的水下模糊效果也仅仅是添加了Depth Of Field特效,用于模拟水下效果,下面有两种触发方式的讲   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=81',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391162404',
    'updatetime' => '1498383340',
    'video_url' => '',
    'hitsid' => 'c-1-81',
    'views' => '1556',
    'yesterdayviews' => '1',
    'dayviews' => '2',
    'weekviews' => '4',
    'monthviews' => '24',
  ),
);
?>