<?php
return array (
  46 => 
  array (
    'id' => '46',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'Unity3d模型导入技巧',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Unity3d 模型 导入',
    'description' => 'Unity3d导入3dMax模型会产生若干问题，按照官方的说明，将max模型导成fbx文件导入untiy似乎也不能解决1、x轴向偏转3dmax模型导入后自动有一...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=46',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319581',
    'updatetime' => '1498139925',
    'video_url' => '',
    'hitsid' => 'c-1-46',
    'views' => '416',
    'yesterdayviews' => '1',
    'dayviews' => '10',
    'weekviews' => '10',
    'monthviews' => '27',
  ),
  52 => 
  array (
    'id' => '52',
    'catid' => '28',
    'typeid' => '0',
    'title' => '使用Kinect测量身高',
    'style' => '',
    'thumb' => 'http://images.cnblogs.com/cnblogs_com/yangecnu/201211/201211120131281176.png',
    'keywords' => '使用 Kinect 测量',
    'description' => '使用Kinect测量身高 使用Kinect测量身高的方法其实有很多种： 第一种方式是使用Kinect的视场角以及结合一些三角形几何运算，就可以大致测...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=28&id=52',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363330782',
    'updatetime' => '1498217338',
    'video_url' => '',
    'hitsid' => 'c-1-52',
    'views' => '401',
    'yesterdayviews' => '1',
    'dayviews' => '7',
    'weekviews' => '15',
    'monthviews' => '16',
  ),
  39 => 
  array (
    'id' => '39',
    'catid' => '24',
    'typeid' => '0',
    'title' => '虚拟现实引擎比较',
    'style' => '',
    'thumb' => '',
    'keywords' => '虚拟现实 引擎 比较',
    'description' => '虚拟现实引擎的好坏问题争论了很久，相信也会一直争论下去，软件的好坏本身就是相对的，因此使用者更应该从自身的角度和所处的行业特点来选...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=24&id=39',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363318602',
    'updatetime' => '1497223834',
    'video_url' => '',
    'hitsid' => 'c-1-39',
    'views' => '1029',
    'yesterdayviews' => '5',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '15',
  ),
  42 => 
  array (
    'id' => '42',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'Unity3D里面的JavaScript和浏览器的JavaScript的大致区别',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Unity3D 里面 JavaScript',
    'description' => '我从前做过一点JavaScript的东西，和同事加起来大概写过将近2M的JavaScript脚本，粗看了一下Unity中的JavaScript，和从前所了解的基于Brows...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=42',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363319291',
    'updatetime' => '1497801453',
    'video_url' => '',
    'hitsid' => 'c-1-42',
    'views' => '261',
    'yesterdayviews' => '6',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '12',
  ),
  55 => 
  array (
    'id' => '55',
    'catid' => '29',
    'typeid' => '0',
    'title' => '安卓手机控制的arduino双足行走机器人',
    'style' => '',
    'thumb' => '',
    'keywords' => '手机 控制 arduino',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=29&id=55',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363335967',
    'updatetime' => '1498229776',
    'video_url' => '',
    'hitsid' => 'c-1-55',
    'views' => '678',
    'yesterdayviews' => '1',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '8',
  ),
  80 => 
  array (
    'id' => '80',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3d之实现全屏窗口 gui焦点不错位 ',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2014/0131/20140131055757870.png',
    'keywords' => 'unity3d 实现 全屏',
    'description' => '关于unity进行全屏窗体的实现例子貌似不多，基本上思路都是用user32 dll来搞定。但是大多数都会出现焦点错位，或者3D画面由于窗口拉伸而变   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=80',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391162251',
    'updatetime' => '1508102486',
    'video_url' => '',
    'hitsid' => 'c-1-80',
    'views' => '1861',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '7',
  ),
  79 => 
  array (
    'id' => '79',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'unity3D中Gui button双击代码方法',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3D button 双击',
    'description' => '一个做双击效果的方法用两个按钮，点1出现2 2里写事件。var a=0 0;var b=0;function OnGUI(){if(a==0){if(GUI Button (Rect(10,10,100   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=26&id=79',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391161856',
    'updatetime' => '1508109863',
    'video_url' => '',
    'hitsid' => 'c-1-79',
    'views' => '2346',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '6',
  ),
  88 => 
  array (
    'id' => '88',
    'catid' => '30',
    'typeid' => '0',
    'title' => 'unity iOS bulid 教程及remote 模式',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity bulid 教程',
    'description' => '常规bulid环境 unity 3 5 b6 pro + xcode 4 2 1 + ipad2 ios5 0 1 从来没有问题设置和安装 provisioning 这步有问题的朋友    ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=30&id=88',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391167932',
    'updatetime' => '1497158163',
    'video_url' => '',
    'hitsid' => 'c-1-88',
    'views' => '169',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '3',
    'monthviews' => '6',
  ),
);
?>