<?php
return array (
  11 => 
  array (
    'id' => '11',
    'catid' => '17',
    'typeid' => '0',
    'title' => '客户经理，销售主管（5年工作经验）',
    'style' => '',
    'thumb' => 'http://img03.zhaopin.cn/2012/other/search/images/apply_btn.png',
    'keywords' => '客户经理',
    'description' => '公司名称：北京朗途科技有限责任公司公司性质：民营公司规模：20人以下公司行业：媒体 出版 影视 文化传播 广告 会展 公关 市场推广 计算   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=17&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358178104',
    'updatetime' => '1508063921',
    'video_url' => '',
    'hitsid' => 'c-1-11',
    'views' => '79',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'unity3d，maya角色动画师',
    'style' => '',
    'thumb' => 'http://img03.zhaopin.cn/2012/other/search/images/apply_btn.png',
    'keywords' => '',
    'description' => '工作经验：3-5年发布日期：2013-03-01最低学历：不限管理经验：否工作性质：全职招聘人数：1人职位月薪：6001-8000元/月职位类别：互联网/...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=17&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358178154',
    'updatetime' => '1508063918',
    'video_url' => '',
    'hitsid' => 'c-1-12',
    'views' => '505',
    'yesterdayviews' => '4',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'unity3d程序员(3年以上工作经验）',
    'style' => '',
    'thumb' => 'http://img03.zhaopin.cn/2012/other/search/images/apply_btn.png',
    'keywords' => 'unity3d 程序员',
    'description' => '公司名称：北京朗途科技有限责任公司公司性质：民营公司规模：20人以下公司行业：媒体/出版/影视/文化传播 广告/会展/公关/市场推广 计算...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=17&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358178179',
    'updatetime' => '1508063915',
    'video_url' => '',
    'hitsid' => 'c-1-13',
    'views' => '104',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>