<?php
return array (
  10 => 
  array (
    'id' => '10',
    'catid' => '18',
    'typeid' => '0',
    'title' => '三维动画展示',
    'style' => '',
    'thumb' => '',
    'keywords' => '三维动画 展示',
    'description' => '三维动画展示',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=18&id=10',
    'listorder' => '10',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358176827',
    'updatetime' => '1465604533',
    'video_url' => 'http://player.youku.com/player.php/sid/XNDAxNTg4MTI4/v.swf',
    'hitsid' => 'c-1-10',
    'views' => '22',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '18',
    'typeid' => '0',
    'title' => '虚拟现实',
    'style' => '',
    'thumb' => '',
    'keywords' => '虚拟现实',
    'description' => '虚拟现实',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=18&id=8',
    'listorder' => '30',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358176750',
    'updatetime' => '1420588734',
    'video_url' => 'http://player.youku.com/player.php/sid/XNTMwMjIwNTEy/v.swf',
    'hitsid' => 'c-1-8',
    'views' => '7',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '18',
    'typeid' => '0',
    'title' => '朗途考试系统',
    'style' => '',
    'thumb' => '',
    'keywords' => '朗途 考试',
    'description' => '朗途考试系统',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=18&id=9',
    'listorder' => '20',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358176790',
    'updatetime' => '1465542594',
    'video_url' => 'http://player.youku.com/player.php/sid/XNTQxNjgzMzgw/v.swf',
    'hitsid' => 'c-1-9',
    'views' => '5',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '18',
    'typeid' => '0',
    'title' => '朗途房产展示',
    'style' => '',
    'thumb' => '',
    'keywords' => '朗途 房产',
    'description' => '朗途房产展示',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=18&id=7',
    'listorder' => '40',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358176689',
    'updatetime' => '1452487510',
    'video_url' => 'http://player.youku.com/player.php/sid/XNTI5MTA3Nzg0/v.swf',
    'hitsid' => 'c-1-7',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>