<?php
return array (
  59 => 
  array (
    'id' => '59',
    'catid' => '15',
    'typeid' => '0',
    'title' => '增强现实展览展示应用',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0326/20130326125353748.jpg',
    'keywords' => '增强现实 展览展示',
    'description' => '国内客户如有视频中类似的需求可以联系北京朗途科技，我们志在打造国内最专业的虚拟现实和增强现实产品   ',
    'posids' => '1',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=15&id=59',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1426739760',
    'updatetime' => '1508109834',
    'video_url' => '',
    'hitsid' => 'c-1-59',
    'views' => '4019',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '4',
  ),
  60 => 
  array (
    'id' => '60',
    'catid' => '15',
    'typeid' => '0',
    'title' => '增强现实图像识别交互',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0326/20130326033218296.jpg',
    'keywords' => '增强现实 图像',
    'description' => '指定图像的识别和判断，根据不同图案的卡片，在显示设备中呈现出不同的预制模型，每张图片都带给你不同的惊奇感受。',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=15&id=60',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1352963580',
    'updatetime' => '1508063924',
    'video_url' => '',
    'hitsid' => 'c-1-60',
    'views' => '424',
    'yesterdayviews' => '1',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '15',
    'typeid' => '0',
    'title' => '增强现实移动端Mobile-AR',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0312/20130312053149733.jpg',
    'keywords' => '增强 现实 移动',
    'description' => '朗途科技打造增强现实软件搭载手机，平板电脑的硬件设备。 根据客户的需求我们可以为您订制研发不同的增强现实产品，可以使原本内容单一的   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=15&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358346660',
    'updatetime' => '1508063904',
    'video_url' => '',
    'hitsid' => 'c-1-5',
    'views' => '251',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '15',
    'typeid' => '0',
    'title' => '增强现实汽车杂志应用',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0326/20130326033541815.jpg',
    'keywords' => '增强现实 汽车',
    'description' => '                            增强现实(AR)产品在很多高新领域做产品发布会时都有广泛应用。汽车，手表，高端...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=15&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1358173946',
    'updatetime' => '1508063911',
    'video_url' => '',
    'hitsid' => 'c-1-6',
    'views' => '156',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>