<?php
return array (
  48 => 
  array (
    'id' => '48',
    'catid' => '27',
    'typeid' => '0',
    'title' => '国产虚拟现实引擎vrp软件支持的功能一览',
    'style' => '',
    'thumb' => '',
    'keywords' => '国产 虚拟现实 引擎',
    'description' => 'vrp软件在经过多年的改版升级，逐渐趋于成熟，虽然和国外的虚拟引擎还存在明显的不足，但和最初的版本还是有了很大程度的提高。以下是此软...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=27&id=48',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363322604',
    'updatetime' => '1497336704',
    'video_url' => '',
    'hitsid' => 'c-1-48',
    'views' => '259',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
  49 => 
  array (
    'id' => '49',
    'catid' => '27',
    'typeid' => '0',
    'title' => '三维模型导入到vrp中报错的处理',
    'style' => '',
    'thumb' => '',
    'keywords' => '三维 模型 导入到',
    'description' => '以下错误提示解决方法如下：●错误提示：错误1:Line01:该模型所使用的第1号MapChannel没有初始化，请给该MapChannel指定正确的Uv坐标。　解...',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=27&id=49',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1363322858',
    'updatetime' => '1507816676',
    'video_url' => '',
    'hitsid' => 'c-1-49',
    'views' => '1695',
    'yesterdayviews' => '4',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>