<?php
return array (
  77 => 
  array (
    'id' => '77',
    'catid' => '25',
    'typeid' => '0',
    'title' => 'unity3d/AR实现方案的对比',
    'style' => '',
    'thumb' => '',
    'keywords' => 'unity3d 实现 方案',
    'description' => 'AR应用忽然就比较流行起来了，这是老外做一个unity3d AR解决方案的对比，有兴趣的朋友可以深入研究下！I have made a system which    ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=25&id=77',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391161378',
    'updatetime' => '1498323088',
    'video_url' => '',
    'hitsid' => 'c-1-77',
    'views' => '2164',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '12',
    'monthviews' => '42',
  ),
  53 => 
  array (
    'id' => '53',
    'catid' => '25',
    'typeid' => '0',
    'title' => '朗途科技增强现实产品简介',
    'style' => '',
    'thumb' => 'http://www.langtuvr.com/uploadfile/2013/0312/20130312054326543.jpg',
    'keywords' => '科技 增强 现实',
    'description' => '朗途科技打造增强现实软件搭载手机，平板电脑的硬件设备。 根据客户的需求我们可以为您订制研发不同的增强现实产品，可以使原本内容单一的   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=25&id=53',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391155200',
    'updatetime' => '1496219594',
    'video_url' => '',
    'hitsid' => 'c-1-53',
    'views' => '258',
    'yesterdayviews' => '1',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '4',
  ),
  76 => 
  array (
    'id' => '76',
    'catid' => '25',
    'typeid' => '0',
    'title' => '高通利用Unity技术扩展增强现实平台',
    'style' => '',
    'thumb' => '',
    'keywords' => '高通 利用 Unity',
    'description' => '圣地亚哥2010年11月10日消息，高通公司宣布其Unity增强现实(简称AR)软件开发包即将上市。高通的UnityAR软件开发包让开发者采用Unity的有奖   ',
    'posids' => '0',
    'url' => 'http://www.langtuvr.com/index.php?m=content&c=index&a=show&catid=25&id=76',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1391161071',
    'updatetime' => '1497265879',
    'video_url' => '',
    'hitsid' => 'c-1-76',
    'views' => '320',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
);
?>